### ISSUE TITLE
AttributeError from terminal when running photobooth.py

### ISSUE THREAD

**Issue by hermantherock** [jrleeman/PiBooth#9]
![2017-10-26-220403_800x600_scrot](https://user-images.githubusercontent.com/33076853/32087544-0b352522-baa2-11e7-90b0-f1943962b052.png)

I commented out the line `#camera.resulotion = (2592, 1944) # 1280,720 also works for some setups 2592,1944
`
and the program will run, but the side effect is the photos are the same resolution of my screen size (800x600)

** While making this post I noticed the word `resulotion` is spelled wrong , so I retyped it as `resolution` and all is well : the program runs and the photos are saved in the much higher resolution of 2592x1944 **

**Comment by jrleeman** [comment]
Oops! I'll get that corrected!
